//! `TextField`'s own clipboard access — ⌘C/⌘X copy the current selection to
//! the system pasteboard, ⌘V reads it back. Deliberately separate from
//! `neko_core::clipboard::pasteboard` (the daemon's clipboard-*history*
//! capture/restore module) even though the shape is nearly identical: this
//! is a one-shot, on-keypress read/write in the *client* process, not a
//! polling loop, and `neko` never depends on `neko-core` at all (see
//! `AGENTS.md`'s crate-layout boundary rule) — the two modules can't share
//! code even if they wanted to.
//!
//! **Every AppKit call here is wrapped in [`objc2::rc::autoreleasepool`],
//! same discipline as `neko_core::clipboard::pasteboard` and
//! `material.rs`** — an unpooled pasteboard call site is exactly the defect
//! class that took the daemon's clipboard-capture loop to 14+ GB resident in
//! the past (see `AGENTS.md`, "Clipboard capture memory"). This module is
//! called far less often (once per real ⌘C/⌘X/⌘V keypress, not a timer), but
//! the same rule applies regardless of call frequency.

#[cfg(target_os = "macos")]
use objc2::rc::autoreleasepool;
#[cfg(target_os = "macos")]
use objc2_app_kit::{
    NSPasteboard, NSPasteboardTypePNG, NSPasteboardTypeString, NSPasteboardTypeTIFF,
};
#[cfg(target_os = "macos")]
use objc2_foundation::NSString;

/// Writes `text` as the pasteboard's sole contents. Returns whether the
/// write succeeded (mirrors `neko_core::clipboard::pasteboard::write_string`'s
/// own return shape).
#[cfg(target_os = "macos")]
pub fn write_string(text: &str) -> bool {
    objc2::rc::autoreleasepool(|_pool| {
        // SAFETY: `NSPasteboardTypeString` is a plain (non-`safe`)
        // `extern "C"` static generated by objc2-app-kit — reading it needs
        // `unsafe` under edition 2024's safe-extern-static rules, but it's
        // just a linker-provided constant pointer with no real invariant to
        // uphold beyond "AppKit is loaded," which it is by construction in
        // this binary. Same reasoning as every other call site in this
        // codebase that reads this constant (`neko_core::clipboard`,
        // `material.rs`).
        unsafe {
            let pb = NSPasteboard::generalPasteboard();
            pb.clearContents();
            let ns = NSString::from_str(text);
            pb.setString_forType(&ns, NSPasteboardTypeString)
        }
    })
}

/// Reads the pasteboard's current plain-text string content, if any. No
/// privacy-marker filtering (unlike `neko_core::clipboard::pasteboard`'s
/// capture-loop read) — a person invoking ⌘V has explicitly asked to paste
/// whatever is on the pasteboard right now, the same way every other text
/// field on the system behaves; the privacy-marker convention exists to keep
/// *background capture* from silently recording a password manager's
/// concealed copy, not to block an explicit, in-the-moment paste.
#[cfg(target_os = "macos")]
pub fn read_string() -> Option<String> {
    objc2::rc::autoreleasepool(|_pool| {
        // SAFETY: same as `write_string` above.
        unsafe {
            let pb = NSPasteboard::generalPasteboard();
            pb.stringForType(NSPasteboardTypeString)
                .map(|s| s.to_string())
        }
    })
}

#[cfg(target_os = "macos")]
/// Reads an image off the pasteboard as PNG bytes, if one is there.
///
/// PNG first, then TIFF — macOS screenshots and most apps put PNG on the
/// board, but `NSPasteboardTypeTIFF` is the older lingua franca that
/// screen-capture and some editors still write, and reading only the first
/// would silently miss half of what people paste.
///
/// Returns the bytes rather than a path: what to *do* with an image is the
/// caller's decision, and the pasteboard is a systemwide resource this module
/// exists to keep every AKit call to.
pub fn read_image() -> Option<Vec<u8>> {
    autoreleasepool(|_| {
        let pb = NSPasteboard::generalPasteboard();
        // SAFETY: both constants are plain (non-`safe`) statics, read here
        // exactly as `NSPasteboardTypeString` is above.
        // SAFETY: both are plain (non-`safe`) extern statics, read here
        // exactly as `NSPasteboardTypeString` is above.
        for kind in unsafe { [NSPasteboardTypePNG, NSPasteboardTypeTIFF] } {
            if let Some(data) = pb.dataForType(kind) {
                let bytes = data.to_vec();
                if !bytes.is_empty() {
                    return Some(bytes);
                }
            }
        }
        None
    })
}

#[cfg(not(target_os = "macos"))]
pub fn write_string(_text: &str) -> bool {
    false
}

#[cfg(not(target_os = "macos"))]
pub fn read_string() -> Option<String> {
    None
}

#[cfg(not(target_os = "macos"))]
pub fn read_image() -> Option<Vec<u8>> {
    None
}
